version: '3'
name: fileserver-proxy

services:
  proxy:
    build: .
    container_name: proxy
    environment:
      - REMOTE=http://<your ip>:30120
    ports:
      - "80:80"
    volumes:
      - ./cache:/srv/cache
